### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by deadpyxel** [c4urself/bump2version#176]
Been using this a lot recently, and with the release of python 3.9 I was wondering if the support is planned for for it.

Recently I've tried to install bump2version in a python3.9 environment, and it gives me a dependency error with pip:
```console
Traceback (most recent call last):
  File "/usr/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==19.3.1' distribution was not found and is required by the application
``` 

IF there's anything I could do to help the support for the new version, please let me know. I think problably some new tests and dependencies will have to be checked before that is possible, but if there's anything I can help with.

**Comment by deadpyxel** [comment]
Little update, turns out that the Archlinux repo upgrade had some problems in updating pip, after doing an `easy_install pip` all seems to be working fine. I'll close this issue for now, since the original intent was to ask for python 3.9 support.
