### ISSUE TITLE
Bump2version is erroring when listing the current version and there is no value to replace in the file. 

### ISSUE THREAD

**Issue by cowboy-cod3r** [c4urself/bump2version#181]
Hi,

I use this product for quite a bit of projects.  Thanks for keeping it up to date.

I recently upgraded from 1.0.0 to 1.0.1 and started getting some errors.  

**Issue**
When attempting to get the current version, when there is no value to replace in one of my managed version files, I started getting this error:
```
# bump2version patch --allow-dirty --dry-run --list | grep current_version | awk -F "=" 'NR==1 { print $2 }'
Traceback (most recent call last):
  File "/Users/humbargs/opt/anaconda3/envs/myid-session-checker-product/bin/bump2version", line 8, in <module>
    sys.exit(main())
  File "/Users/humbargs/opt/anaconda3/envs/myid-session-checker-product/lib/python3.8/site-packages/bumpversion/cli.py", line 124, in main
    _check_files_contain_version(files, current_version, context)
  File "/Users/humbargs/opt/anaconda3/envs/myid-session-checker-product/lib/python3.8/site-packages/bumpversion/cli.py", line 618, in _check_files_contain_version
    f.should_contain_version(current_version, context)
  File "/Users/humbargs/opt/anaconda3/envs/myid-session-checker-product/lib/python3.8/site-packages/bumpversion/utils.py", line 68, in should_contain_version
    raise VersionNotFoundException(
bumpversion.exceptions.VersionNotFoundException: Did not find 'versionToken' in file: 'deploy/files/versions.csv'
```

The above error is correct in that `versionToken` does not exist in the file `deploy/files/versions.csv`.  Prior to `v1.0.1` being released though it would ignore that and return me the current version.  Here is an example of it working with version 1.0.0.

```
bump2version patch --allow-dirty --dry-run --list | grep current_version | awk -F "=" 'NR==1 { print $2 }'
1.0.3
``` 

As part of my own CI process, I have a requirement to get the current version of the product I'm building so that I can name things appropriately based on version which is why I'm trying to get the current version.  Is there a better approach to get the current version?

**Comment by florisla** [comment]
Hi,

Would this proposed argument work for you?

https://github.com/c4urself/bump2version/issues/57

**Comment by cowboy-cod3r** [comment]
Yes, I believe that would work.  Thanks!
